[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/var/log/supervisor

[program:xvnc]
command=su student -c "Xvnc :1 -geometry %(ENV_VNC_RESOLUTION)s -depth %(ENV_VNC_DEPTH)s -rfbport 5901 -SecurityTypes VncAuth -PasswordFile /home/student/.vnc/passwd -AlwaysShared"
autorestart=true
priority=100
stdout_logfile=/var/log/supervisor/vnc.log
stderr_logfile=/var/log/supervisor/vnc_err.log

[program:xfce]
command=su student -c "env DISPLAY=:1 startxfce4"
autorestart=true
priority=200
stdout_logfile=/var/log/supervisor/xfce.log
stderr_logfile=/var/log/supervisor/xfce_err.log

[program:novnc]
command=websockify --web /usr/share/novnc 6080 localhost:5901
autorestart=true
priority=300
stdout_logfile=/var/log/supervisor/novnc.log
stderr_logfile=/var/log/supervisor/novnc_err.log
